### ISSUE TITLE
Spawned mission vehicles exploding?

### ISSUE THREAD

**Issue by cikez** [SMVampire/DZMS-DayZMissionSystem#35]
Hey Vampire.. I am wondering if you have heard anyone else report this issue.. I have a pretty busy server running 1.8.0.3 with RC1.1 of DZMS on it and players are complaining about DZMS spawned vehicles at the missions are "exploding". They are saying it is killing them when they get into the vehicles. Any ideas on this? Thanks.

**Comment by ebayShopper** [comment]
ac419dc
