### ISSUE TITLE
Loot boxes doesn't spawn or spawn empty

### ISSUE THREAD

**Issue by daetoya** [SMVampire/DZMS-DayZMissionSystem#46]
Missions are running but seems like they are either not spawning lootboxes or spawning them without any loot.
RPT logs:
18:58:12 [DZMS]: Running Minor Mission SM3.
18:58:12 "z\addons\dayz_server\system\scheduler\sched_corpses.sqf: Deleted 0 uncontrolled zombies, 0 uncontrolled animals, 0 dead character bodies and 1 empty groups. Added 0 flies."
18:58:17 Unrecognized CfgVehicles simulation  in bin\config.bin/CfgVehicles/USBasicAmmunitionBox/
18:58:17 Cannot create entity with abstract type USBasicAmmunitionBox (scope = private?)
18:58:17 Cannot create non-ai vehicle USBasicAmmunitionBox,
18:58:17 Cannot create entity with abstract type USBasicAmmunitionBox (scope = private?)
18:58:17 Cannot create non-ai vehicle USBasicAmmunitionBox,

**Comment by SMVampire** [comment]
@zoviq Are you running DayZ: Epoch or something different? Which version?

**Comment by zoviq** [comment]
@SMVampire I am running DayZ mod 1.8.8. Tried changing USBasicAmmunitionBox to DZ_ExplosiveBoxRU etc but still the same problem.

**Comment by zoviq** [comment]
So, should i wait for fix or I am able to do something myself? @SMVampire @ebayShopper

**Comment by zoviq** [comment]
?

**Comment by zoviq** [comment]
@ebayShopper thanks a lot!
